CREATE DATABASE IF NOT EXISTS seata_order DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS seata_storage DEFAULT CHARACTER SET utf8mb4;
USE seata_order;
CREATE TABLE IF NOT EXISTS demo_order(id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,decision_number INT NOT NULL,status VARCHAR(20) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS undo_log(branch_id BIGINT NOT NULL,xid VARCHAR(128) NOT NULL,context VARCHAR(128) NOT NULL,rollback_info LONGBLOB NOT NULL,log_status INT NOT NULL,log_created DATETIME(6) NOT NULL,log_modified DATETIME(6) NOT NULL,UNIQUE KEY ux_undo_log(xid,branch_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
USE seata_storage;
CREATE TABLE IF NOT EXISTS demo_storage(id BIGINT PRIMARY KEY,stock INT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO demo_storage(id,stock) VALUES(1,100) ON DUPLICATE KEY UPDATE stock=stock;
CREATE TABLE IF NOT EXISTS undo_log(branch_id BIGINT NOT NULL,xid VARCHAR(128) NOT NULL,context VARCHAR(128) NOT NULL,rollback_info LONGBLOB NOT NULL,log_status INT NOT NULL,log_created DATETIME(6) NOT NULL,log_modified DATETIME(6) NOT NULL,UNIQUE KEY ux_undo_log(xid,branch_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;